apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
  labels:
    release: prometheus
type: Opaque
stringData:
  slack_webhook_url: 'https://hooks.slack.com/services/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'

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: global-alert-manager-configuration
  namespace: monitoring
  labels:
    release: prometheus
spec:
  route:
    groupBy: ['alertname']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    continue: true
    receiver: 'slack-notification'
    routes:
      - receiver: 'slack-notification'
        continue: true
  receivers:
    - name: 'slack-notification'
      slackConfigs:
        - channel: 'grafana-dev-alerts'
          apiURL:
            name: slack-webhook
            key: slack_webhook_url
          title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
          text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"